### ISSUE TITLE
Cue  parameter Setter

### ISSUE THREAD

**Issue by DrVagrov** [Omadel/Etienne#6]
la possibilité de setter les valeurs, de volume par exemple, des paramètres

**Comment by Omadel** [comment]
- [x] C'est fait, maintenant on peut dans les soundparameters setter toutes les valeurs que tu veux.

        public void SetAudioMixerGroup(AudioMixerGroup audioMixerGroup)
        public void SetPriority(int priority)        
        public void SetVolume(float volume)        
        public void SetPitch(float pitch)        
        public void SetStereoPan(float stereoPan)        
        public void SetSpacialBlend(int spacialBlend)        
        public void SetMinDistance(float minDistance)        
        public void SetMaxDistance(float maxDistance)
